@webhook = https://webhook.site/126fef0e-ee5f-4952-94d7-404985c22889

### Access token endpoint
# @name login
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}
&scope=3db474b9-6a0c-4840-96ac-1fceb342124f/.default
&client_secret={{clientSecret}}
&grant_type=client_credentials

### Issuance
POST https://verifiedid.did.msidentity.com/v1.0/verifiableCredentials/createIssuanceRequest
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "callback": {
        "url": "https://ce4a76b5b73d298f17b9802887e94e4f.m.pipedream.net",
        "state": "my-state",
        "headers": {
            "api-key": "my-api-key"
        }
    },
    "authority": "did:web:azir-entra-issuer.pages.dev",
    "registration": {
        "clientName": "Mighty Issuer"
    },
    "type": "VerifiedEmployee",
    "manifest": "https://verifiedid.did.msidentity.com/v1.0/tenants/{{tenantId}}/verifiableCredentials/contracts/8449b104-a942-2c72-1ffe-8a18acfbbafe/manifest"
}

### Presentation
POST https://verifiedid.did.msidentity.com/v1.0/verifiableCredentials/createPresentationRequest
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
  "includeReceipt": true,
  "authority": "did:web:azir-entra-issuer.pages.dev",
  "registration": {
    "clientName": "Mighty verifier"
  },
  "callback": {
    "url": "{{webhook}}",
    "state": "my-verification-state",
    "headers": {
      "api-key": "my-api-key"
    }
  },
  "requestedCredentials": [
    {
      "type": "VerifiedEmployee",
      "purpose": "So we can see that you are an employee",
      "acceptedIssuers": [
        "did:web:azir-entra-issuer.pages.dev"
      ],
      "configuration": {
        "validation": {
          "allowRevoked": false,
          "validateLinkedDomain": true
        }
      }
    }
  ]
}